[build]
  # Tunjukkan lokasi folder functions
  functions = "functions" 
  # Perintah untuk menginstal dependensi
  command = "npm install" 

[functions]
  node_bundler = "esbuild"

# --- ATURAN REDIRECT UTAMA ---

[[redirects]]
  # Tangkap semua traffic yang menuju subdomain short.nurts.xyz
  # Anda harus mengatur DNS untuk subdomain ini
  from = "https://short.nurts.xyz/*"
  # Arahkan semua traffic ke fungsi shortener.js
  to = "/.netlify/functions/shortener" 
  status = 200 # Ini hanya untuk internal Netlify, fungsi yang menentukan status akhir (302)
  force = true 

[[redirects]]
  # Redirect root path ke index.html untuk menampilkan antarmuka
  from = "/"
  to = "/index.html"
  status = 200