[build]
  functions = "functions" 
  command = "npm install" 

[functions]
  node_bundler = "esbuild"

# --- ATURAN REDIRECT UTAMA ---

[[redirects]]
  # Redirect /api/create ke fungsi shortener
  from = "/api/create"
  to = "/.netlify/functions/shortener"
  status = 200 # status internal
  force = true

[[redirects]]
  # Redirect semua path lainnya (yang bukan file statis) ke fungsi. 
  # Ini menangani /slug-pendek
  from = "/*"
  to = "/.netlify/functions/shortener" 
  status = 200
